from enum import Enum

class Transaction(Enum):
    Image = 'transaction'
    SuccessMSG = 'خرید با موفقیت انجام شد'
    Warning = 'اخطار'
    CancelMSG = 'تراکنش لغو شد'
    FailMSG = 'تراکنس ناموفق'

class Store(Enum):
    ItemSuccess = 'با موفقیت ارسال شد'
    ItemFail = ''
    Service = 'با موفقیت اعمال شد'
    CharacterNotSelected = 'لطفا کاراکتر خود را انتخاب کنید'
    CharacterOnline = 'اکانت باید آفلاین باشد'
    NotEnoughToken = 'مقدار توکن کافی نمی باشد'
    CharacterLevel = 'کاراکتر باید لول {level} باشد'
    buy = 'خرید'
    Profession = 'شما این شغل را حرفه را یاد نگرفته اید'
    Token = 'توکن'
    Empty = 'کاراکتری پیدا نشد'

class MSGList(Enum):
    EmptyFields = 'لطفا تمام فیلدها پر شود'
    EmptyRedeemCode = 'لطفا کد بازخرید خود را وارد نمایید'
    WrongPassword = 'پسورد وارد شده صحیح نمی باشد'
    WrongPasswordOrEmail = 'آدرس ایمیل یا رمز عبور اشتباه می باشد'
    ChangepasswordError = ''
    EmailNotExist = 'آدرس ایمیل یا شماره تماس اشتباه یا موجود نمی باشد'
    TrySendSMS = 'پیامک ارسال شده است برای ارسال مجدد کمی صبر کنید'
    DisableEmail = 'سرویس ایمیل غیر فعال می باشد'
    WrongCode = 'کد وارد شده اشتباه می باشد'
    ComparePassword = 'رمز عبور با تکرار رمز عبور متفاوت می باشد'
    EmailInUsed = 'آدرس ایمیل قبلا استفاده شده'
    WrongPhoneNumberFromat = 'شماره تلفن وارد شده صحیح نمی باشد'
    ThisCodeIsUsed = 'این کد استفاده شده است'
    RedeemcodeUse = 'با موفقیت ثبت شد'
    WrongRecruitFriendCode = 'کد دعوت نامه اشتباه می باشد'
    PageNotFoundTitle = 'Sorry page not exist'
    PageNotFoundDetail = 'the page you looking for does not exist'
    Warningtitle = 'Warning'
    WarningDetail = 'An error has occurred in system'
    RegisterSuccessDetail = 'Created successfully'
    RegisterSuccessTitle = 'Create account'
    ChangePasswordTitle = 'Change password'
    ChangePasswordChangedDetail = 'با موفقیت انجام شد'

class Forms(Enum):
    buytoken = 'Buy token'
    login = 'Log in'
    redeemcode = 'Redeem code'
    redeemcodecode = 'کد باز خرید'
    email = 'Email address'
    password = 'Password'
    captcha = 'Captcha'
    firstname = 'Firstname'
    lastname = 'Lastname'
    phonenumber = 'Phone number'
    username = 'Username '
    repassword = 'Confirm password'
    oldpassword = 'Old password'
    newpassword = 'New password'
    renewpassword = 'Confirm password'
    register = 'Create an account'
    changepassword = 'Change password'
    EnterCode = 'Code'
    Submit = 'Submit'
    EnterPhoneNumber = 'Phone number'
    SendCode = 'Send'
    WrongEmailFormat = 'Wrong email address format'
    WrongPhoneNumberOrEmail = 'آدرس ایمیل یا شماره تلفن اشتباه می باشد'
    createcode = 'Create code'
    frindcode = 'بر روی دکمه ساخت کد کلیک کنید تا کد ساخته شود'
    SOAPConnectionError = 'در سیستم خطا رخ داده است'
    Choose= 'Choose'
    Buy = 'Buy'
    UsernameExist = 'نام کاربری قبلا ساخته شده'
    Send = 'Send'
    Post = 'Post'
    TitlePost = 'عنوان پست'
    DetailPost = 'جزئیات پست'
    PostBug = 'ثبت باگ'
    DetailBug = 'عنوان'
    KindofBug = 'نوع'
    
class Console(Enum):
    FlaskRunning = 'Flask framework is running on {ip}:{port}'
    FlaskError = 'Flask framework cannot run'
    Logout = 'account {email} logout from {ip}'
    LoginSuccess = 'Login: account {email} login from {ip}'
    RegisterSuccess = 'Registeration successfuly for {email}'
    RegisterFailed = 'Registeration Failed'
    ConnSQLError = 'Error while connecting to MySQL {ip}'
    ConnSQLSuccess = 'Connected to MySQL Server version {res}'
    RealmFailed = 'Connection failed for realm: {ip}'
    Vistors = 'Someone, visit with this ip address: {ip}'
    LogClrear = 'Log.txt file hase been cleaned by core for this run'
    Load = 'Loaded {number} from {table} in {time} second(s)'
    Error = 'Somethings not working to get client ip'
    Admin = 'Admin authorized with {ip} to open admin page'
    STASMS = 'Send a message to {contact_count}'
    DebugOff = 'Debug mode is Off'
    DebugOn = 'Debug mode is ON'
    RemoveAllCaptchas = 'Captcha iamge deleted Successfuly'
    NetworkInfo = 'Server local ip address is {ip}'

class SOAPCS(Enum):
    url = 'http://{ip}:7878'
    Item = 'send item {character} "StormWoW Shop" "Az entekhab shoma mamnonim. StormWoW.ir" {itemid}'
    ServiceFaction = 'character changefaction {character}'
    ServiceRace = 'character changerace {character}'
    UsernameChangePassword = 'account set password {username} {newpassword} {newpassword}'
    BTChangePAssword = 'bnetaccount set password {email} {newpassword} {newpassword}'
    BTAccountCreate = 'bnetaccount create {email} {password}'
    AccountCreate = 'account create {username} {password}'
    Gold = 'send money {character} "StormWoW Shop" "Az entekhab shoma mamnonim. StormWoW.ir" {gold}'
    CharacterLevel = 'character level {character} 80'
    soaperror = 'SOAP Connection failed to {ip}'
    SOAPCE = 'Connection erorr'
    
class SMSS(Enum):
    RecoveryPassword = 'کد بازیابی کلمه عبور اکانت شما {code} \n stormwow.ir'
    Error = 'Check internet connection for SMS Request'